config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'categories#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users do
    resources :categories do
      resources :expenses
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :joins, dependent: :destroy
  has_many :expenses, through: :joins

  validates :name, :icon, presence: true, length: { maximum: 50 }

  def total_expenses(user)
    expenses.where(user_id: user.id).sum(:amount) || 0
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to user_categories_path(current_user), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>

  <p>
    <strong>User:</strong>
    <%= category.user_id %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: [current_user, category]) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<% if user_signed_in? %>
  <div class="page-header">
    <h2>Categories</h2>
  </div>
  <p style="color: green"><%= notice %></p>
  <div id="categories" class="categories">
    <% if @categories.any? %>
      <ul class="list-cat">
        <% @categories.each do |category| %>
          <li>
            <%= category.icon %>
          </li>
          <li>
             <%= link_to category.name, user_category_expenses_path(current_user, category) %>
          </li>
        <% end %>
        
      </ul>
    <% else %>
      <p>No categories yet. <%= link_to "Create one", new_user_category_path(current_user) %></p>
    <% end %>
  </div>

  <%= link_to "New category", new_user_category_path(current_user) %>
<% else %>
  <div>
    <h3 class="alert-msg">You are not signed in</h3>
    <p class="alert-info">You need to Sign in to see your categories or Sign up if you don't have an account yet.</p>
    <p class="alert-info">Click on side menu to Sign in or Sign up.</p>
  </div>
<% end %>

app/views/categories/new.html.erb
<div class="page-header">
  <h2>New category</h2>
</div>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", user_categories_path(current_user) %>
</div>>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>